[package]
name = 'Decimal'
version = '1.0.0'

[addresses]
decimal = "0xdb495ff915af4ab6cb6a011cb64349b41442068a578e35e25e2fff6990c7c30f"

[dependencies]
AptosFramework = { local = "../../../../framework/aptos-framework" }
